# Generated by Django 3.1.7 on 2021-03-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='author',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='body',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='created_at',
        ),
        migrations.AddField(
            model_name='feed',
            name='url',
            field=models.URLField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='feed',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
